REPLY = """Content-type: text/html

<html><title>Languages</title>
<body>
<h1>Hello World selector</h1>
<p>Similar to file <a href="../languages.html">languages.html</a>,
but this page is dynamically generated by a Python CGI script, using
selction list and input field names imported from a common Python module
on the server. Only the common module must be maintained as ne languages are
added, because it is shared ith the reply script.

To see the code that generates this page and reply, click
<a href="getfile.py?filename=cgi-bin\languages2.py">here</a>,
<a href="getfile.py?filename=cgi-bin\languagesreply.py">here</a>,
<a href="getfile.py?filename=cgi-bin\languages2common.py">here</a>, and
<a href="getfile.py?filename=cgi-bin\\formMockup.py">here</a>.</p>
<hr>
<form method="POST" action="languages2reply.py">
    <p><b>Select a programming language:</b></p>
    <p><select name="%s">
            <option>All</option>
            %s
            <option>Other</option>
        </select>
    </p>
    <p><input type="submit" value="Submit Query"></p>
</form>
</body></html>
"""

from languages2common import inputkey, hellos

options = []
for lang in hellos:
    options.append('<option>%s</option>' % lang)
options = '\n\t\t\t'.join(options)
print(REPLY % (inputkey, options))